const express = require('express')
const router = express.Router()
const crypto = require('crypto')
const token = require('jsonwebtoken')
const Usermodel = require('../models/user')
const { sentOtp, VerifyOtp, logout, alluser, getuser, getAuth, updateUser, getadmin } = require('../controllers/authController')
const { preventReLogin, isLoggedIn, ISUser, Isadmin } = require('../middlewares/authmiddlwares')
router.post('/signup/sent-otp',preventReLogin,sentOtp)
router.post('/signup/verify-otp',VerifyOtp)
router.get('/logout',logout)
router.get('/alluser',alluser)
router.get('/getuser',isLoggedIn,getuser)
router.get('/check-auth',ISUser,getAuth)
router.post('/update-user',isLoggedIn,updateUser)
router.get('/check-admin',Isadmin,getadmin)
module.exports = router